### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ssss404** [outime/tweetdeck-activity-muter#1]
Hi,
is there any chance you could update this to work again? It's exactly what I've been looking for.

**Comment by outime** [comment]
Yeah why not, I’ll take a look this week.--
Rubén Díaz
GPG id 2354DA5F

**Comment by outime** [comment]
Yeah why not, I’ll take a look this week.

**Comment by outime** [comment]
Yeah why not. I’ll take a look this week.

**Comment by outime** [comment]
I took a look and I made some changes ~locally~ [here](https://github.com/outime/tweetdeck-activity-muter/commit/3af496ee8c8a93c6ee0ed40b65ab1af054c93578) so it at least builds now. A lot has changed in TweetDeck in the last 6 years and it doesn't look that straightforward as before so let's see if I have enough free time to deal with it.

**Comment by outime** [comment]
@ssss404 this should be working now. I'll publish a new version to the store soon. It may take a while to appear online since the review process is much longer than back then.

**Comment by ssss404** [comment]
Thanks a lot!

**Comment by outime** [comment]
@ssss404 it's live: https://chrome.google.com/webstore/detail/tweetdeck-activity-muter/miaoojdjohgmgkibpkidjcmokjcbanle/

**Comment by ssss404** [comment]
Here's something I noticed:

Any new actions by muted users show up in the Activity column. The same applies if you scroll down to load more tweets.

**Comment by outime** [comment]
@ssss404 I just saw your comment by pure chance, I didn’t get notified. Can you open up another issue for that? I’ll try to get it fixed. I actually released a new version today and I could’ve taken a look at it.
