### ISSUE TITLE
New activity is not being filtered

### ISSUE THREAD

**Issue by ssss404** [outime/tweetdeck-activity-muter#2]
- New actions by muted users show up in the Activity column. The same applies if you scroll down to load more tweets.

- Issue above leads to this: muted users who mass spam actions (e.g. liking birthday wishes) make the activity column go haywire with constant refreshes. It only happened twice so far and only on very long "like" chains. Here's a video of it: https://streamable.com/f4pf1n

**Comment by outime** [comment]
Thanks for reporting @ssss404 I'll check during this week.

**Comment by outime** [comment]
@ssss404 fixed in v1.6.1 which will be published in the web store at some point. You can also manually download it from [here](https://github.com/outime/tweetdeck-activity-muter/releases/tag/v1.6.1) but it won't be auto-updated.
