### ISSUE TITLE
Refresh bug from issue #2 still occurring

### ISSUE THREAD

**Issue by ssss404** [outime/tweetdeck-activity-muter#5]
Muted users' actions make the activity column go haywire with constant refreshes. It only happens if you load more tweets by scrolling down or by clicking

Here's a new video: https://streamable.com/mph4gt

It's easy to reproduce by muting the last active users (5 should be enough).

Version v1.6.2 was tested.

**Comment by ssss404** [comment]
Sometimes it's not constantly flashing like shown in the video but not loading more tweets either.

**Comment by outime** [comment]
@ssss404 there's now improved logic that should at least avoid the repeated refreshing. As a temporal workaround for too many muted users it'll now request a second activity page and then apply the filtering so it has more entries to filter from and won't disable the autorefresh when scrolling down.
